### PR TITLE
Update readme file with how to configure and use the project

### PR DESCRIPTION
**Pull request by fabiosoaresv**
### What this PR make?
Update README with:
- What this project ?
- How to configure?
- How to use?

### CODE REVIEW

**Comment by amanjiofficial** [comment]
@xavier9909 could you review this once

**Comment by xavier9909** [comment]
> @xavier9909 could you review this once
 i have already sent you a merging requst for readme

**Comment by amanjiofficial** [comment]
Due to recent changes in the repository there are some merge conflicts. Can you please resolve them so that I can merge the pull request. @fabiosoaresv

**Comment by fabiosoaresv** [comment]
@amanjiofficial _done_ :smile: 

@xavier9909 I think the readme with screenshots it's not recommended, and they aren't align, if you want, you could to open another PR to remove screenshots and write the commands lines or configuration.

**Comment by xavier9909** [comment]
> @amanjiofficial _done_ 😄
> 
> @xavier9909 I think the readme with screenshots it's not recommended, and they aren't align, if you want, you could to open another PR to remove screenshots and write the commands lines or configuration.

Its alrdy merged (it is  rcmmnded)

**Pull request merged**
